### ISSUE TITLE
New LG TV's have keycode in IP Control

### ISSUE THREAD

**Issue by rbcet** [bentemple/nvidia_shield_tv_controller#2]
Telnet closes itself after connection, probably because the new keycode thing.

There is another project https://github.com/WesSouza/lgtv-ip-control,

can we implement this logic into this project?

**Comment by bentemple** [comment]
@rbcetin you willing to help me test some stuff? I don't have an LG tv, so hard for me to verify if something is working.

**Comment by rbcet** [comment]
Yep I can help you

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> @rbcetin you willing to help me test some stuff? I don't have an LG tv, so hard for me to verify if something is working.
I guess the time for the LG integration was a bit short. Unfortunately, I can not establish a telnet connection, but find the project ingenious.

I have specially fetched the new ShiledTV remote 2019 (the one with the Netflix button) and only then discovered this git here.
This allows me to define the menu button. One option of the Shield for this is to switch through the HDMI channels. I don't understand why nvidia can't have more IR codes trained. VOL+- works fine on my Onkyo even when the Shield is off.

Nice work @bentemple 

I would be happy to contribute my knowledge here but am now not so the Android code professional :D
Is this the last change to this topic?
https://github.com/bentemple/nvidia_shield_tv_controller/commit/fe63899d9097188f0fef029f1abb91edb2cf3ebb

If I hadn't found this git here, I probably would have tried this and then addressed my HomeAssistant (HTTP POST/GET) and run individual commands on the TV:
https://f-droid.org/en/packages/io.github.sds100.keymapper/

The connection between HomeAssistant and LG is working fine:
https://www.home-assistant.io/integrations/webostv/
https://www.youtube.com/watch?v=LFr7JrVYe-A

**Comment by bentemple** [comment]
Yeah, I haven't done any more. seems like it would almost be more universal to forward commands from the shield to homeassistant, and let home assistant control the TV? obviously my setup doesn't support the latest LG tvs and I haven't gotten around to fixing it, but home assistant is pretty universal, so if we just invoke home assistant commands from "tiles" on the nvidia shield UI that would probably be quite easy to get working and pretty useful...

**Comment by bentemple** [comment]
OK, so I was able to use the same integration with my home assistant setup. So I'll be creating a configuration / updating the code in the coming days or weeks to connect to home assistant. 

I'm sure you've moved on from this, but if you're still interested, the update is coming :) 

HA is far more universal, so I figure by supporting it, people can leverage this to control a lot more things much more easily.

Then you can just add an event driven automation and do whatever you want in HA.

Here's what my automation basically looks like: 

```
 id: '1721312106762'
  alias: Nvidia Shield Input Source Controller
  description: ''
  trigger:
  - platform: event
    event_type: nvidia_shield_tv_request
    event_data: {}
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "playstation" }}'
      sequence:
      - service: media_player.select_source
        target:
          device_id: 82320ac14909b682c69011be87520f89
        data:
          source: Playstation 4
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "shield" }}'
      sequence:
      - service: media_player.select_source
        target:
          device_id: 82320ac14909b682c69011be87520f89
        data:
          source: Nvidia Shield
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "nintendo_switch" }}'
      sequence:
      - service: media_player.select_source
        target:
          device_id: 82320ac14909b682c69011be87520f89
        data:
          source: Nintendo Switch
  mode: single
```

Note: I have renamed my HDMI inputs to Nintendo Switch. If you haven't done that, it'll probably just be HDMI-1 or something.
